version: 2
updates:
  - package-ecosystem: gomod
    directory: /services/device-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: /services/policy-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: /services/command-service
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /services/admin-api
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm

  - package-ecosystem: npm
    directory: /services/admin-console
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
