package handler

import (
	"encoding/json"
	"io"
	"log/slog"
	"time"

	"github.com/google/uuid"
	"github.com/sermetkartal/mdm/services/remote-control-service/internal/model"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// SignalingStreamMessage is the gRPC message type for the bidirectional signaling stream.
// In production this would be generated by protobuf; defined here as a stand-in.
type SignalingStreamMessage struct {
	SessionID string `json:"session_id"`
	Type      string `json:"type"`    // offer, answer, candidate, bye, quality_change
	Payload   string `json:"payload"` // SDP or ICE candidate JSON
}

// SignalingService implements the gRPC bidirectional signaling stream for devices.
type SignalingService struct {
	handler *RemoteHandler
}

func NewSignalingService(handler *RemoteHandler) *SignalingService {
	return &SignalingService{handler: handler}
}

// RegisterGRPC registers the signaling service with the gRPC server.
func (s *SignalingService) RegisterGRPC(server *grpc.Server) {
	// In production, this would register the protobuf-generated service.
	// For now, the bidirectional stream is implemented via the StreamHandler below.
	slog.Info("gRPC signaling service registered")
}

// HandleDeviceStream handles a bidirectional gRPC signaling stream from a device.
// The device sends its session_id in the first message to identify itself.
func (s *SignalingService) HandleDeviceStream(stream grpc.BidiStreamingServer[SignalingStreamMessage, SignalingStreamMessage]) error {
	// First message must contain the session_id
	firstMsg, err := stream.Recv()
	if err != nil {
		return status.Error(codes.InvalidArgument, "expected initial message with session_id")
	}

	sessionID, err := uuid.Parse(firstMsg.SessionID)
	if err != nil {
		return status.Error(codes.InvalidArgument, "invalid session_id")
	}

	slog.Info("device connected to signaling stream", "session_id", sessionID)

	deviceCh, ok := s.handler.relay.GetDeviceChannel(sessionID)
	if !ok {
		return status.Error(codes.NotFound, "no signaling channel for session")
	}

	// Forward messages from signaling relay to device (messages TO device)
	done := make(chan struct{})
	go func() {
		defer close(done)
		for msg := range deviceCh {
			grpcMsg := &SignalingStreamMessage{
				SessionID: msg.SessionID.String(),
				Type:      string(msg.Type),
				Payload:   msg.Payload,
			}
			if err := stream.Send(grpcMsg); err != nil {
				slog.Debug("gRPC stream send failed", "error", err)
				return
			}
		}
	}()

	// Read messages from device and relay (messages FROM device)
	for {
		msg, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			slog.Debug("gRPC stream recv ended", "session_id", sessionID, "error", err)
			break
		}

		sigMsg := model.SignalingMessage{
			SessionID: sessionID,
			Type:      model.MessageType(msg.Type),
			From:      "device",
			To:        "admin",
			Payload:   msg.Payload,
			Timestamp: time.Now(),
		}

		if err := s.handler.HandleSignaling(sigMsg); err != nil {
			slog.Error("failed to handle device signaling message", "error", err)
		}
	}

	<-done
	slog.Info("device disconnected from signaling stream", "session_id", sessionID)
	return nil
}

// ICEServersResponse returns the configured ICE servers as JSON for device configuration.
func (s *SignalingService) GetICEServersJSON() (string, error) {
	servers := s.handler.GetICEServers()
	data, err := json.Marshal(servers)
	if err != nil {
		return "", err
	}
	return string(data), nil
}
